[package]
name = "mrCache"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = "0.23.3"
tonic = "0.10.2"
tokio = { version = "1.34.0", features = ["full"] }
prost = "0.12.3"

serde = {version = "1.0.193", features = ["derive"]}

[build-dependencies]
tonic-build = "0.10.2"